steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Push
  args:
  - 'builds'
  - 'submit'
  - '--tag'
  - 'gcr.io/$PROJECT_ID/api-urlinsane-com'
  waitFor:
  - '-'
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  args:
  - 'beta'
  - 'run'
  - 'deploy'
  - '--region=us-central1'
  - 'api-urlinsane-com'
  - '--image'
  - 'gcr.io/$PROJECT_ID/api-urlinsane-com'
  - '--allow-unauthenticated'
  - '--memory=512Mi'
  - '--concurrency=2'
  waitFor:
  - 'Push'
